import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GridBack from "./components/common/GridBack";
import NavBar from "./components/common/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "WEBSY",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
       <link 
         href="https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&family=Righteous&display=swap" 
         rel="stylesheet" 
         preconnect="true"
       />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GridBack>
          <NavBar/>
        {children}
        </GridBack>
      </body>
    </html>
  );
}
