import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GridBack from "./components/common/GridBack";
import NavBar from "./components/common/NavBar";
import CustomCursor from "./components/common/CustomCursor";
import ScrollToTop from "./components/common/ScrollToTop";
import AosInit from "./components/common/AosInIt";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "WEBSY",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
       <link href="https://fonts.googleapis.com/css2?family=Righteous&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"/>

      </head>

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AosInit/>
        <ScrollToTop/>
          <CustomCursor/>
          <GridBack>
            <NavBar />
            {children}
          </GridBack>
      </body>
    </html>
  );
}
